/**
 * 案例数据 - 全局唯一数据源
 * 共34条案例：宝马20条、奔驰12条、保时捷2条
 * 图片路径已对齐到七牛新文件夹结构：
 *   宝马外观: images/baomawaiguan/
 *   奔驰外观: images/benchiwaiguan/
 *   保时捷外观: images/baoshijiewaiguan/
 */

const CASE_DATA = [
  // ===== 宝马升级 (20条) =====
  {
    id: 1,
    brand: '宝马升级',
    category: '外观',
    carModel: 'BMW 5 Series F18',
    upgradeTarget: '10-17款升级22款',
    title: '宝马5系 F18 10-17款升级22款运动版（无损款）',
    description: '老款5系升级为22款最新外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、后杠尾喉尾唇全套升级。无损安装，保留原车结构，外观全面焕新至最新款运动风格。',
    tags: ['无损安装', '22款大灯', '前杠包围', '尾灯升级', '后杠尾喉'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥10,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款运动版本外观后面-白色.jpg',
    showFallback: false
  },
  {
    id: 2,
    brand: '宝马升级',
    carModel: 'BMW 5 Series F18',
    upgradeTarget: '10-17款升级22款M5',
    title: '宝马5系 F18 10-17款升级22款M5版本（切割版）',
    description: '老款5系升级为22款M5运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、尾箱盖、22款后杠尾喉尾唇。后叶子板切割钣金工艺，外观全面升级至22款M5风格。',
    tags: ['切割工艺', '22款M5', '运动包围', '尾箱升级', '钣金'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '尾箱盖', '22款后杠尾喉尾唇', '后叶子板切割钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥16,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/运动版本外观正面-灰色.jpg',
    showFallback: false
  },
  {
    id: 3,
    brand: '宝马升级',
    carModel: 'BMW 5 Series F18',
    upgradeTarget: '10-17款升级25款',
    title: '宝马5系 F18 10-17款升级25款运动版（无损款）',
    description: '老款5系升级为25款最新外观，含25款大灯、前叶子板、机盖、25款前杠中网包围、25款尾灯、后杠尾喉尾唇。无损安装，外观全面升级至25款最新运动风格。',
    tags: ['无损安装', '25款大灯', '25款包围', '运动风格', '尾灯升级'],
    parts: ['25款大灯', '前叶子板', '机盖', '25款前杠中网包围', '25款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥17,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款运动版外观背面-黑色2.jpg',
    showFallback: false
  },
  {
    id: 4,
    brand: '宝马升级',
    carModel: 'BMW 5 Series F18',
    upgradeTarget: '10-17款升级25款',
    title: '宝马5系 F18 10-17款升级25款运动版（切割版）',
    description: '老款5系升级为25款运动外观，含25款大灯、前叶子板、机盖、25款前杠中网包围、25款尾灯、后杠尾喉尾唇。后叶子板切割钣金，外观全面升级至25款最新风格。',
    tags: ['切割工艺', '25款大灯', '运动包围', '钣金', '尾喉尾唇'],
    parts: ['25款大灯', '前叶子板', '机盖', '25款前杠中网包围', '25款尾灯', '后杠尾喉尾唇', '后叶子板切割钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥21,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/尾灯尾部切割款外观侧面-黑色1.jpg',
    showFallback: false
  },
  {
    id: 5,
    brand: '宝马升级',
    carModel: 'BMW 5 Series G38',
    upgradeTarget: '18-20款升级22款',
    title: '宝马5系 G38 18-20款升级22款（无损款）',
    description: '18-20款5系升级为22款外观，含22款大灯、22款前杠中网包围、22款尾灯。无损安装，外观焕新至22款最新风格。',
    tags: ['无损安装', '22款大灯', '前杠包围', '尾灯升级', '入门之选'],
    parts: ['22款大灯', '22款前杠中网包围', '22款尾灯'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥6,200',
    imageTheme: 'theme-bmw',
    image: '/images/baomaneishi/22款小菱格座椅纹路版型-波尔多红1.jpg',
    showFallback: false
  },
  {
    id: 6,
    brand: '宝马升级',
    carModel: 'BMW 7 Series F02',
    upgradeTarget: '09-15款升级22款',
    title: '宝马7系 F02 09-15款升级22款运动版（无损款）',
    description: '老款7系升级为22款运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、后杠尾喉尾唇。无损安装保留原车结构。',
    tags: ['无损安装', '22款大灯', '运动包围', '尾灯升级', '后杠尾喉'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥15,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款运动版外观正面-黑色.jpg',
    showFallback: false
  },
  {
    id: 7,
    brand: '宝马升级',
    carModel: 'BMW 7 Series F02',
    upgradeTarget: '09-15款升级22款',
    title: '宝马7系 F02 09-15款升级22款运动版（切割版）',
    description: '老款7系升级为22款运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、后杠尾喉尾唇、尾箱盖。后尾灯部位钣金工艺，外观全面升级。',
    tags: ['切割钣金', '22款大灯', '运动包围', '尾箱盖', '尾灯升级'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '后杠尾喉尾唇', '尾箱盖', '后尾灯部位钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥24,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/切割款运动版外观正面-黑色.jpg',
    showFallback: false
  },
  {
    id: 8,
    brand: '宝马升级',
    carModel: 'BMW 7 Series F02',
    upgradeTarget: '09-15款升级24款',
    title: '宝马7系 F02 09-15款升级24款（切割版）',
    description: '老款7系升级为24款最新外观，含24款大灯、前叶子板、机盖、24款前杠中网包围、24款尾灯、后杠尾喉尾唇、尾箱盖。后尾灯部位钣金工艺，外观全面升级至24款最新风格。',
    tags: ['24款最新', '切割钣金', '运动包围', '尾箱盖', '尾灯升级'],
    parts: ['24款大灯', '前叶子板', '机盖', '24款前杠中网包围', '24款尾灯', '后杠尾喉尾唇', '尾箱盖', '后尾灯部位钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥35,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/切割版外观侧面-黑色1.jpg',
    showFallback: false
  },
  {
    id: 9,
    brand: '宝马升级',
    carModel: 'BMW 7 Series G12',
    upgradeTarget: '16-20款升级22款',
    title: '宝马7系 G12 16-19款升级22款运动版（无损款）',
    description: '16-19款7系升级为22款运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、后杠尾喉尾唇。无损安装，外观全面升级至22款风格。',
    tags: ['无损安装', '22款大灯', '运动包围', '16-19款', '旗舰升级'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥15,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款行政版外观后面-黑色.jpg',
    showFallback: false
  },
  {
    id: 10,
    brand: '宝马升级',
    carModel: 'BMW X5 E70',
    upgradeTarget: '08-13款升级24款',
    title: '宝马X5 E70 08-13款升级24款运动版（无损款）',
    description: '老款X5升级为24款运动外观，含24款大灯、前叶子板、机盖、24款前杠中网包围、24款尾灯。无损安装，外观升级至24款风格。',
    tags: ['无损安装', '24款大灯', '运动包围', 'SUV升级', '尾灯升级'],
    parts: ['24款大灯', '前叶子板', '机盖', '24款前杠中网包围', '24款尾灯'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥16,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/25款运动版本无损-外观侧面-咖色.jpg',
    showFallback: false
  },
  {
    id: 11,
    brand: '宝马升级',
    carModel: 'BMW X5 E70',
    upgradeTarget: '08-13款升级24款X5M',
    title: '宝马X5 E70 08-13款升级24款X5M版本（切割版）',
    description: '老款X5升级为24款X5M运动外观，含24款大灯、前叶子板、机盖、X5M前杠中网包围、24款尾灯、后杠尾喉尾唇、尾箱盖。后尾灯部位钣金工艺，外观全面升级至24款X5M风格。',
    tags: ['X5M升级', '切割钣金', '24款大灯', '运动包围', '锻造轮毂'],
    parts: ['24款大灯', '前叶子板', '机盖', 'X5M前杠中网包围', '24款尾灯', '后杠尾喉尾唇', '尾箱盖', '后尾灯部位钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥24,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/25款运动版本-外观侧面2-黑色.jpg',
    showFallback: false
  },
  {
    id: 12,
    brand: '宝马升级',
    carModel: 'BMW X5 E70',
    upgradeTarget: '14-19款升级24款',
    title: '宝马X5 E70 14-19款升级24款运动版（无损款）',
    description: '14-19款X5升级为24款运动外观，含24款大灯、前叶子板、机盖、24款前杠中网包围、24款尾灯。无损安装，外观升级至24款风格。',
    tags: ['无损安装', '24款大灯', '运动包围', 'SUV升级', '14-19款'],
    parts: ['24款大灯', '前叶子板', '机盖', '24款前杠中网包围', '24款尾灯'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥16,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/25款X5运动版本-外观侧面-黑色.jpg',
    showFallback: false
  },
  {
    id: 13,
    brand: '宝马升级',
    carModel: 'BMW X5 F15',
    upgradeTarget: '14-17款升级24款',
    title: '宝马X5 F15 14-17款升级24款（无损款）',
    description: '14-17款X5升级为24款外观，含24款大灯、前叶子板、机盖、24款前杠中网包围、24款尾灯、尾箱盖、24款后杠尾喉尾唇。无损安装，外观全面升级至24款风格。',
    tags: ['无损安装', '24款大灯', '前杠包围', '尾箱盖', 'SUV升级'],
    parts: ['24款大灯', '前叶子板', '机盖', '24款前杠中网包围', '24款尾灯', '尾箱盖', '24款后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥19,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomaneishi/25款大菱格座椅版型-波尔多红1.jpg',
    showFallback: false
  },
  {
    id: 14,
    brand: '宝马升级',
    carModel: 'BMW X6 E71',
    upgradeTarget: '08-13款升级24款X6M',
    title: '宝马X6 E71 08-13款升级24款X6M版本（切割版）',
    description: '老款X6升级为24款X6M运动外观，含24款大灯、前叶子板、机盖、X6M前杠中网包围、24款尾灯、后杠尾喉尾唇、尾箱盖。后尾灯部位钣金工艺，外观全面升级至24款X6M风格。',
    tags: ['X6M升级', '切割钣金', '24款大灯', '运动包围', '尾箱盖'],
    parts: ['24款大灯', '前叶子板', '机盖', 'X6M前杠中网包围', '24款尾灯', '后杠尾喉尾唇', '尾箱盖', '后尾灯部位钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥24,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/25款X6M版本 4出尾喉-外观侧面-白色2.jpg',
    showFallback: false
  },
  {
    id: 15,
    brand: '宝马升级',
    carModel: 'BMW X6 F16',
    upgradeTarget: '14-17款升级24款X6M',
    title: '宝马X6 F16 14-17款升级24款X6M版本（切割版）',
    description: '14-17款X6升级为24款X6M运动外观，含24款大灯、前叶子板、机盖、X6M前杠中网包围、24款尾灯、后杠尾喉尾唇、尾箱盖。后尾灯部位钣金工艺，外观全面升级至24款X6M风格。',
    tags: ['X6M升级', '切割钣金', '24款大灯', '运动包围', '14-17款'],
    parts: ['24款大灯', '前叶子板', '机盖', 'X6M前杠中网包围', '24款尾灯', '后杠尾喉尾唇', '尾箱盖', '后尾灯部位钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥34,800',
    imageTheme: 'theme-bmw-dark',
    image: '/images/baomawaiguan/25款X6运动版双出尾喉-外观侧面-黑色2.jpg',
    showFallback: false
  },
  {
    id: 16,
    brand: '宝马升级',
    carModel: 'BMW 3 Series F35',
    upgradeTarget: '10-17款升级22款',
    title: '宝马3系 F35 10-17款升级22款（无损款）',
    description: '老款3系升级为22款运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围、22款尾灯、后杠尾喉尾唇。无损安装，外观焕新至最新款M运动风格。',
    tags: ['无损安装', '22款大灯', 'M运动包围', '尾灯升级', '性价比首选'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围', '22款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥8,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款-外观侧面-白色2.jpg',
    showFallback: false
  },
  {
    id: 17,
    brand: '宝马升级',
    carModel: 'BMW 5 Series GT F07',
    upgradeTarget: '10-17款升级22款M5',
    title: '宝马5系GT F07 10-17款升级22款M5版本（无损款）',
    description: '老款5系GT升级为22款M5运动外观，含22款大灯、前叶子板、机盖、22款前杠中网包围。无损安装，外观全面升级至22款M5风格。',
    tags: ['无损安装', 'M5风格', 'GT升级', '22款大灯', '运动包围'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥9,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/22款GT M5版本-尾灯无损款运动版本外观后面-黑色.jpg',
    showFallback: false
  },
  {
    id: 18,
    brand: '宝马升级',
    carModel: 'BMW 5 Series GT F07',
    upgradeTarget: '10-17款升级22款6系GT',
    title: '宝马5系GT F07 10-17款升级22款6系GT版本（无损款）',
    description: '老款5系GT升级为22款6系GT外观，含22款大灯、前叶子板、机盖、22款前杠中网包围。无损安装，外观全面升级至22款6系GT豪华风格。',
    tags: ['无损安装', '6系GT', 'GT升级', '22款大灯', '豪华风格'],
    parts: ['22款大灯', '前叶子板', '机盖', '22款前杠中网包围'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥18,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/22款6GT版本外观正面-红紫色.jpg',
    showFallback: false
  },
  {
    id: 19,
    brand: '宝马升级',
    carModel: 'BMW X3 F25',
    upgradeTarget: '12-17款升级23款',
    title: '宝马X3 F25 12-17款升级23款（无损款）',
    description: '12-17款X3升级为23款外观，含23款大灯、前叶子板、机盖、23款前杠中网包围、23款尾灯、后杠尾喉尾唇。无损安装，外观全面升级至23款最新风格。',
    tags: ['无损安装', '23款大灯', '前杠包围', 'SUV升级', '尾灯升级'],
    parts: ['23款大灯', '前叶子板', '机盖', '23款前杠中网包围', '23款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥18,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款-外观尾灯-黑色.jpg',
    showFallback: false
  },
  {
    id: 20,
    brand: '宝马升级',
    carModel: 'BMW X3 F25',
    upgradeTarget: '18-20款升级23款',
    title: '宝马X3 F25 18-20款升级23款（无损款）',
    description: '18-20款X3升级为23款外观，含23款大灯、前叶子板、23款前杠中网包围、23款尾灯、后杠尾喉尾唇。无损安装，外观升级至23款风格。',
    tags: ['无损安装', '23款大灯', '运动包围', 'SUV升级', '18-20款'],
    parts: ['23款大灯', '前叶子板', '23款前杠中网包围', '23款尾灯', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥15,800',
    imageTheme: 'theme-bmw',
    image: '/images/baomawaiguan/尾灯无损款-外观正面-黑色1.jpg',
    showFallback: false
  },

  // ===== 奔驰升级 (12条) =====
  {
    id: 21,
    brand: '奔驰升级',
    carModel: 'Mercedes S-Class W221',
    upgradeTarget: '06-13款升级20款迈巴赫',
    title: '奔驰S级 W221 06-13款升级20款迈巴赫（切割版）',
    description: '老款S级升级为20款迈巴赫外观，含20款迈巴赫大灯、前叶子板、机盖、迈巴赫前杠中网包围、20款尾灯、尾箱盖、20款尾杠和尾喉尾唇。后叶子板切割钣金，整车升级为迈巴赫豪华风格。',
    tags: ['迈巴赫升级', '切割钣金', '迈巴赫大灯', '前后包围', '尾箱盖'],
    parts: ['20款迈巴赫大灯', '前叶子板', '机盖', '迈巴赫前杠中网包围', '20款尾灯', '尾箱盖', '20款尾杠和尾喉尾唇', '后叶子板切割钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥15,800',
    imageTheme: 'theme-benz',
    image: '/images/benchiwaiguan/20款 S63AMG 版本一比一尾灯切割版-外观正面-黑色.jpg',
    showFallback: false
  },
  {
    id: 22,
    brand: '奔驰升级',
    carModel: 'Mercedes S-Class W221',
    upgradeTarget: '06-13款升级20款迈巴赫',
    title: '奔驰S级 W221 06-13款升级20款迈巴赫（无损款）',
    description: '老款S级无损升级为20款迈巴赫外观，含20款迈巴赫大灯、前叶子板、机盖、迈巴赫前杠中网包围、20款尾灯、20款尾杠和尾喉尾唇。无损安装不切割，外观升级为迈巴赫风格。',
    tags: ['无损安装', '迈巴赫升级', '迈巴赫大灯', '前后包围', '不切割'],
    parts: ['20款迈巴赫大灯', '前叶子板', '机盖', '迈巴赫前杠中网包围', '20款尾灯', '20款尾杠和尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥12,800',
    imageTheme: 'theme-benz-light',
    image: '/images/benchiwaiguan/20款迈巴赫无损款尾灯（无损款只有迈巴赫款）-外观正面-黑色.jpg',
    showFallback: false
  },
  {
    id: 23,
    brand: '奔驰升级',
    carModel: 'Mercedes S-Class W221',
    upgradeTarget: '06-13款升级24款迈巴赫',
    title: '奔驰S级 W221 06-13款升级24款迈巴赫版本（切割版）',
    description: '老款S级升级为24款迈巴赫外观，含24款大灯、24款尾灯、迈巴赫前后杠包围、中网、前叶子板、机盖、后叶子板、4个隐藏式门把手、4个门皮、24款倒车镜、油箱盖、侧裙。切割钣金工艺，外观全面升级至24款迈巴赫风格。',
    tags: ['24款最新', '迈巴赫升级', '切割钣金', '隐藏门把手', '鹦鹉油漆'],
    parts: ['24款大灯', '24款尾灯', '迈巴赫前后杠包围', '中网', '前叶子板', '机盖', '后叶子板', '4个隐藏式门把手', '4个门皮', '24款倒车镜', '油箱盖', '侧裙'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '鹦鹉335光油油漆',
    price: '¥35,000',
    imageTheme: 'theme-benz',
    image: '/images/benchiwaiguan/25款S450版本-外观侧面-黑色1.jpg',
    showFallback: false
  },
  {
    id: 24,
    brand: '奔驰升级',
    carModel: 'Mercedes S-Class W222',
    upgradeTarget: '14-18款升级20款迈巴赫',
    title: '奔驰S级 W222 14-17款升级20款迈巴赫（无损款）',
    description: '14-17款S级无损升级20款迈巴赫外观，含20款迈巴赫大灯、前包围中网、尾杠、后杠尾喉尾唇。无损安装不切割，外观全面升级为迈巴赫风格。',
    tags: ['无损安装', '迈巴赫包围', '大连屏', '氛围灯', '涡轮出风口'],
    parts: ['20款迈巴赫大灯', '前包围中网', '尾杠', '后杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥7,800',
    imageTheme: 'theme-benz-light',
    image: '/images/benchiwaiguan/20款迈巴赫版本-外观正面-黑色.jpg',
    showFallback: false
  },
  {
    id: 25,
    brand: '奔驰升级',
    carModel: 'Mercedes S-Class W222',
    upgradeTarget: '14-18款升级24款迈巴赫',
    title: '奔驰S级 W222 14-19款升级24款迈巴赫版本（切割版）',
    description: '14-19款S级升级为24款迈巴赫外观，含24款大灯、24款尾灯、迈巴赫前后杠包围、中网、前叶子板、机盖、后叶子板、4个隐藏式门把手、4个门皮、24款倒车镜、侧裙。切割钣金工艺，外观全面升级至24款迈巴赫。',
    tags: ['24款最新', '迈巴赫升级', '切割钣金', '隐藏门把手', '鹦鹉油漆'],
    parts: ['24款大灯', '24款尾灯', '迈巴赫前后杠包围', '中网', '前叶子板', '机盖', '后叶子板', '4个隐藏式门把手', '4个门皮', '24款倒车镜', '侧裙'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '鹦鹉335光油油漆',
    price: '¥35,000',
    imageTheme: 'theme-benz',
    image: '/images/benchiwaiguan/25款迈巴赫版本-外观尾灯-黑色.jpg',
    showFallback: false
  },
  {
    id: 27,
    brand: '奔驰升级',
    carModel: 'Mercedes GL W166',
    upgradeTarget: '13-19款升级25款GLS迈巴赫',
    title: '奔驰GL W166 13-19款升级25款GLS迈巴赫（无损款）',
    description: '13-19款GL升级为25款GLS迈巴赫外观，含25款大灯、前叶子板、机盖、迈巴赫前杠中网包围、25款尾灯、尾箱盖、尾杠尾喉尾唇。无损安装不切割，外观全面升级为迈巴赫豪华SUV风格。',
    tags: ['无损安装', '迈巴赫包围', '25款大灯', 'SUV升级', '豪华风格'],
    parts: ['25款大灯', '前叶子板', '机盖', '迈巴赫前杠中网包围', '25款尾灯', '尾箱盖', '尾杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥19,800',
    imageTheme: 'theme-benz',
    image: '/images/benchiwaiguan/25款GLS迈巴赫版本-尾灯无损款-外观侧面3.jpg',
    showFallback: false
  },
  {
    id: 28,
    brand: '奔驰升级',
    carModel: 'Mercedes ML W164',
    upgradeTarget: '06-12款升级19款AMG',
    title: '奔驰ML W164 06-12款升级19款AMG（切割版）',
    description: '老款ML升级为19款AMG运动外观，含19款大灯、前叶子板、机盖、19款AMG前杠中网包围、19款尾灯、尾箱盖、尾杠尾喉尾唇。后叶子板切割钣金，外观全面升级至19款AMG风格。',
    tags: ['AMG升级', '切割钣金', '19款大灯', '运动包围', 'SUV升级'],
    parts: ['19款大灯', '前叶子板', '机盖', '19款AMG前杠中网包围', '19款尾灯', '尾箱盖', '尾杠尾喉尾唇', '后叶子板切割钣金'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥19,800',
    imageTheme: 'theme-benz-dark',
    image: '/images/benchiwaiguan/尾灯无损款-外观侧面-黑色2.jpg',
    showFallback: false
  },
  {
    id: 29,
    brand: '奔驰升级',
    carModel: 'Mercedes ML/GLE W166',
    upgradeTarget: '13-19款升级25款AMG',
    title: '奔驰ML/GLE W166 13-19款升级25款AMG（无损款）',
    description: '13-19款ML/GLE升级为25款AMG运动外观，含25款大灯、前叶子板、机盖、25款AMG前杠中网包围、25款尾灯、尾箱盖、尾杠尾喉尾唇。无损安装，外观全面升级至25款AMG风格。',
    tags: ['无损安装', 'AMG升级', '25款大灯', '运动包围', 'SUV升级'],
    parts: ['25款大灯', '前叶子板', '机盖', '25款AMG前杠中网包围', '25款尾灯', '尾箱盖', '尾杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥23,800',
    imageTheme: 'theme-benz-dark',
    image: '/images/benchiwaiguan/25款GLEAMG版本-外观尾灯-黑色.jpg',
    showFallback: false
  },
  {
    id: 30,
    brand: '奔驰升级',
    carModel: 'Mercedes E-Class W212',
    upgradeTarget: '10-15款升级23款',
    title: '奔驰E级 W212 10-15款升级23款豪华版（无损款）',
    description: '老款E级升级为23款豪华外观，含23款大灯、前叶子板、机盖、23款豪华版前杠中网包围、23款尾灯、尾箱盖、尾杠尾喉尾唇。无损安装，外观焕新至23款豪华风格。',
    tags: ['无损安装', '23款大灯', '豪华包围', '尾灯升级', '尾箱盖'],
    parts: ['23款大灯', '前叶子板', '机盖', '23款豪华版前杠中网包围', '23款尾灯', '尾箱盖', '尾杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥13,800',
    imageTheme: 'theme-benz',
    image: '/images/benchiwaiguan/23款迈巴赫版-尾灯无损款-外观尾灯.jpg',
    showFallback: false
  },
  {
    id: 31,
    brand: '奔驰升级',
    carModel: 'Mercedes E-Class W213',
    upgradeTarget: '16-19款升级23款',
    title: '奔驰E级 W213 16-19款升级23款豪华版（无损款）',
    description: '16-19款E级升级为23款豪华外观，含23款大灯、23款豪华版前杠中网包围、23款尾灯、尾箱盖、尾杠尾喉尾唇。无损安装，外观全面升级至23款风格。',
    tags: ['无损安装', '23款大灯', '豪华包围', '尾灯升级', '尾箱盖'],
    parts: ['23款大灯', '23款豪华版前杠中网包围', '23款尾灯', '尾箱盖', '尾杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥7,800',
    imageTheme: 'theme-benz-light',
    image: '/images/benchiwaiguan/23款迈巴赫版-尾灯无损款-外观正面.jpg',
    showFallback: false
  },
  {
    id: 32,
    brand: '奔驰升级',
    carModel: 'Mercedes E-Class W213',
    upgradeTarget: '16-19款升级25款AMG',
    title: '奔驰E级 W213 16-19款升级25款AMG版本（无损款）',
    description: '16-19款E级升级为25款AMG运动外观，含25款大灯、前叶子板、机盖、25款豪华版前杠中网包围、25款尾灯、尾箱盖、尾杠尾喉尾唇。无损安装，外观全面升级至25款AMG风格。',
    tags: ['无损安装', 'AMG升级', '25款大灯', '运动包围', '前叶子板'],
    parts: ['25款大灯', '前叶子板', '机盖', '25款豪华版前杠中网包围', '25款尾灯', '尾箱盖', '尾杠尾喉尾唇'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥19,800',
    imageTheme: 'theme-benz-dark',
    image: '/images/benchineis/新款AMG座椅纹路版型-20款一比一中控台-橙色1.jpg',
    showFallback: false
  },

  // ===== 保时捷升级 (2条) =====
  {
    id: 33,
    brand: '保时捷升级',
    carModel: 'Porsche Panamera',
    upgradeTarget: '10-16款升级23款Turbo S',
    title: '保时捷帕拉梅拉 10-16款升级23款Turbo S',
    description: '老款帕拉梅拉升级为23款Turbo S外观，含23款前脸矩阵大灯、23款Turbo S前杠总成、23款机盖、23款前叶子板、23款尾部贯穿尾灯和三段式尾翼、23款尾箱盖、尾杠散件全套。外观全面升级至23款最新风格。',
    tags: ['Turbo S', '矩阵大灯', '贯穿尾灯', '三段尾翼', '前杠总成'],
    parts: ['23款前脸矩阵大灯', '23款Turbo S前杠总成', '23款机盖', '23款前叶子板', '23款尾部贯穿尾灯', '三段式尾翼', '23款尾箱盖', '尾杠散件全套'],
    installType: '切割钣金',
    oldParts: '旧件回收',
    paintInfo: '含配件局部喷漆',
    price: '¥39,800',
    imageTheme: 'theme-porsche',
    image: '/images/baoshijiewaiguan/外观正面-底漆.jpg',
    showFallback: false
  },
  {
    id: 34,
    brand: '保时捷升级',
    carModel: 'Porsche Cayenne',
    upgradeTarget: '11-17款升级25款',
    title: '保时捷卡宴 11-17款升级25款（无损款）',
    description: '老款卡宴升级为25款最新外观，含25款矩阵大灯、25款前杠总成、25款机盖、25款前叶子板、25款贯穿式尾灯（无损款）、尾箱盖、后杠尾喉尾唇和后轮眉。无损安装，外观全面升级至25款最新风格。',
    tags: ['无损安装', '矩阵大灯', '贯穿尾灯', '25款包围', '大连屏'],
    parts: ['25款矩阵大灯', '25款前杠总成', '25款机盖', '25款前叶子板', '25款贯穿式尾灯', '尾箱盖', '后杠尾喉尾唇', '后轮眉'],
    installType: '无损安装',
    oldParts: '旧件归还',
    paintInfo: '含配件局部喷漆',
    price: '¥27,800',
    imageTheme: 'theme-porsche',
    image: '/images/baoshijiewaiguan/外观正面-蓝色.jpg',
    showFallback: false
  }
]

module.exports = { CASE_DATA }
